### PR TITLE
Implementation of SpannerConnectionMetadata done.

### PR DESCRIPTION
**Pull request by itssanjib**
Please validate my changes or merge.

### CODE REVIEW

**Comment by itssanjib** [comment]
@googlebot I signed it!

Best Regards,
Sanjib Pal
Cell: +91 8159938535

**Comment by itssanjib** [comment]
@googlebot <https://github.com/googlebot> I signed it!

Best Regards,
Sanjib Pal
Cell: +91 8159938535

**Comment by elefeint** [comment]
I suspect that you signed with an e-mail address that's different from your commit e-mail address, which is set to your work e-mail. You will likely need to amend the last commit with the correct personal e-mail.

**Comment by elefeint** [comment]
Did you mean to close the PR and open a new one?

**Pull request closed without merging**
