### PR TITLE
Preparing next snapshot version 1.2.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by suztomo**
We merge this once we confirm new release 1.1.0 is available in Maven Central https://repo1.maven.org/maven2/com/google/cloud/cloud-spanner-r2dbc/

### CODE REVIEW

**Comment by suztomo** [comment]
Not yet. https://repo1.maven.org/maven2/com/google/cloud/cloud-spanner-r2dbc/

**Comment by suztomo** [comment]
https://repo.maven.apache.org/maven2/com/google/cloud/cloud-spanner-r2dbc/1.1.0/ is ready.

**Comment by chanseokoh** [comment]
Why is it `1.2.0-SNAPSHOT` instead of `1.1.1-SNAPSHOT`?

**Review by dzou — APPROVED** [review]

**Comment by suztomo** [comment]
@chanseokoh Elena said bumping minor version for snapshot is the convention of this repository.

**Pull request merged**
